install:
- pip install -r requirements.txt -t src/
language: python
script: publish/make-zip.sh
deploy:
  provider: s3
  bucket: "mps-test-lambda1"
dd:
  secure: Dks4PM3uNOFSL+9Xo7TY5IifH2CF02yxXsOjGU2IKWeEPueTn4pAwLZAE3raKVm5Tw7jVJQ3AI2emtOWVQl5le+ezN+eXhMMtbUGm5x7gSQ6t6iVyDywdMY7ttMKW1afrfhToeUps4YJP96S8v32S53Fah0j4CuMqRMua8NEwDJJcROP3CzreuXcL/9GsLhsG7nX3GZbn/haOrYVIOl7BeYj8qllo7XgmT2gofi/uSsx8Bvi6KEymYAH4GUZVbQicfsQcZlxLIMBTAqeA8EReCcNX0lBYjhs+FWe4BOtrxVoe0F5SyNPcBZ5mdF74vPEErtOCqUloisMTOlBX/Re/ks0COXZ01zHETS7V0F95dqVPuKykP0uaq2bNeo1QMe+0fYUp8BWLQFd1s+6YVrMQ0w49YeBXRNRn/GtjxmqWbzsXN8th0tBsXTN/nViS0+CqKi67og7ioxE9+gjK/dyT5/cq0b981KV7Em4PdtTR1+YDqwvMBer419Le5ovfIA76TEGmwnQ4IVdj+QqA1BD074eBwboFzIPmZvQfPhXFsKwQQ/EPNBhScP4liGxu8CeGFyyV6lWW/cJvMsD1qalSgVeDqtk51biSKU9Imt9ntsGI+UTIBQUNUIAN7kwXGDH0979PeOCEcqv4TZ7kvSf5uP8AmwNKFBmp+KaniZspbU=
