install:
- pip install -r requirements.txt -t src/
language: python
script: publish/make-zip.sh
deploy:
  provider: s3
  bucket: "mps-test-lambda1"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  local-dir: dist/
  skip_cleanup: true
after_success:
  - pip install awscli
  - mkdir ~/.aws && echo "[default]" > ~/.aws/config
  - echo "aws_access_key_id = ${AWS_ACCESS_KEY}" >> ~/.aws/config
  - echo "aws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}" >> ~/.aws/config
  - echo "region = $AWS_REGION" >> ~/.aws/config
after_deploy:
  - aws lambda update-function-code  --function-name mpsTestLambda1 --debug --s3-bucket ${AWS_BUCKET} --s3-key lambda-test1.zip
