install:
- pip install -r requirements.txt -t src/
language: python
script: publish/make-zip.sh
deploy:
  provider: s3
  bucket: "mps-test-lambda1"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY

