install:
- pip install -r requirements.txt -t src/
language: python
script: publish/make-zip.sh
deploy:
  provider: s3
  bucket: "mps-test-lambda1"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  local-dir: dist/
  skip_cleanup: true
after_success:
  - pip install awscli
  - env
  - aws lambda update-function-code --debug --region us-east-1 --function-name mpsTestLambda1 --s3-bucket mps-test-lambda1 --s3-key lambda-test1.zip
